# Generated by Django 5.0.1 on 2024-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0002_alter_article_content_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinflip',
            name='side',
            field=models.CharField(default='tail', max_length=5),
        ),
    ]
