# Generated by Django 5.0.1 on 2024-01-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0005_alter_coinflip_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptwo.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptwo.author')),
            ],
        ),
    ]
