# Generated by Django 5.0 on 2023-12-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinFlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(default='head', max_length=5)),
                ('time_stamp', models.TimeField(auto_now=True)),
            ],
        ),
    ]
