# Generated by Django 5.0 on 2023-12-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('birthday', models.TimeField()),
                ('fullname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='coinflip',
            name='side',
            field=models.CharField(default='tail', max_length=5),
        ),
    ]
