# Generated by Django 5.0 on 2023-12-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_coinflip_side_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinflip',
            name='side',
            field=models.CharField(default='tail', max_length=5),
        ),
    ]
