# Generated by Django 5.0 on 2023-12-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_coinflip_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coinflip',
            name='side',
            field=models.CharField(default='head', max_length=5),
        ),
    ]
